# Site settings
title: xorrr blog
email: your-email@domain.com
description: "Musings of a guy"
baseurl: ""
url: "http://xorrr.github.io"
username: "xorrr"

# Build settings
markdown: kramdown
permalink: pretty
